@startsalt
caption vista menu principal tareas del día seleccionado
{
{+
        {/ tareas del día |<u><color:blue> tareas del mes }
        [crear tarea]
fecha actual: Domingo 26/12/2025
[tareas del día: Domingo 26/12/2025 <&calendar>]
   {+
        * 20:00 Entregar vestido
   }
   
}
}
@endsalt