@startsalt
caption vista menú principal 
{
    {+
        {/ tareas del día |<u><color:blue> tareas del mes }
        [crear tarea]
        fecha actual: lunes 20/12/2025
        [tareas del día: lunes 20/12/2025 <&calendar>]
        {SI
            {+
                * 9:00 Ir a la escuela
                * 11:15 Ir al banco
            }
        }
    }
}
@endsalt