@startsalt
caption vista menu principal. Tarea creada
{
    {+
        {/ tareas del día |<u><color:blue> tareas del mes }
        [crear tarea]
        fecha actual: lunes 20/12/2025
        [tareas del día: lunes 05/01/2026 <&calendar>]
        {+
            * 13:30 Comprar verduras
        }

    }
}
@endsalt