@startsalt
caption vista seleccionar mes para ver tareas
{
    {+
        {/ <u><color:blue>tareas del día | tareas del mes }
        [crear tarea]
            {+
                [<&arrow-thick-left>]|**Diciembre 2025**|[<&arrow-thick-right>]|
            }
            {SI
                {#
                    Mié 15 | . 
                    <b><color:blue> Jue 16 | {
                        * 17:00 Comprar comida para el perro | [Editar] | [Quitar]
                        }
                    Vie 17 | . 
                    Sáb 18 | .
                    Dom 19 | .
                    <b><color:blue>Lun 20 | {
                        * 9:00 Ir a la facultad | [Editar] | [Quitar]
                        * 11:00 Ir al banco | [Editar] | [Quitar]
                        }
                    Mar 21 | .
                    Mié 22 | .

                }
            }
            referencia:
            *<b><color:blue>Tiene tareas
    }
}
@endsalt